#!/usr/bin/python3

def raise_exception():
    print ("a" + 3)
